version: "3.9"
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64
    container_name: app_frontend
    volumes:
      - './frontend:/app'
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    platform: linux/x86_64
    container_name: app_backend
    command: npm run start
    ports:
      - ${BACKEND_PORT}:3001
    volumes:
      - './backend:/app'
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=market
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=market
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE