version: "3"
services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - ${PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=market
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE